[package]
name = "eventio"
version = "0.1.0"
authors = ["Min Kim <msk@dolbo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
